Sprint 21. Install room db, add favorite tracks list
Semiteplov/PlaylistMaker pull request #14
Opened 2024-03-28 18:34 UTC by Semiteplov

2024-03-28 22:53 UTC, DmitrijEgorow requested changes

2024-03-28 22:53 UTC, DmitrijEgorow commented on app/src/main/res/layout/fragment_favorites.xml
> +        android:id="@+id/rcFavoriteTracks"
Часть идентификаторов написана через нижнее подчеркивание, стоит унифицировать

2024-03-28 22:53 UTC, DmitrijEgorow commented on app/src/main/java/com/example/playlistmaker/media/ui/fragments/FavoriteTracksFragment.kt
>      private val binding get() = _binding!!
Как раз по схожей причине приложение падает при переключении с поиска на медиатеку

https://github.com/Semiteplov/PlaylistMaker/assets/36837067/85cb60ec-4ce6-46af-b40d-a9b3385727d1

```
FATAL EXCEPTION: main  
Process: com.example.playlistmaker, PID: 11896  
java.lang.NullPointerException  
at com.example.playlistmaker.search.ui.fragments.SearchFragment.getBinding(SearchFragment.kt:26)  
at com.example.playlistmaker.search.ui.fragments.SearchFragment.access$getBinding(SearchFragment.kt:24)  
at com.example.playlistmaker.search.ui.fragments.SearchFragment$updateSearchUI$2.invokeSuspend(SearchFragment.kt:189)  
at com.example.playlistmaker.search.ui.fragments.SearchFragment$updateSearchUI$2.invoke(Unknown Source:8)  
at com.example.playlistmaker.search.ui.fragments.SearchFragment$updateSearchUI$2.invoke(Unknown Source:2)  
at com.example.playlistmaker.utils.Debouncer$requestDebounce$1.invokeSuspend(Debouncer.kt:34)  
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)  
at kotlinx.coroutines.DispatchedTaskKt.resume(DispatchedTask.kt:233)  
at kotlinx.coroutines.DispatchedTaskKt.dispatch(DispatchedTask.kt:166)  
at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:474)  
at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:508)  
at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl$default(CancellableContinuationImpl.kt:497)  
at kotlinx.coroutines.CancellableContinuationImpl.resumeUndispatched(CancellableContinuationImpl.kt:595)  
at kotlinx.coroutines.android.HandlerContext[scheduleResumeAfterDelay](tex://scheduleResumeAfterDelay)[inlined](tex://inlined)Runnable$1.run(Runnable.kt:19)  
at android.os.Handler.handleCallback(Handler.java:938)  
at android.os.Handler.dispatchMessage(Handler.java:99)  
at android.os.Looper.loopOnce(Looper.java:226)  
at android.os.Looper.loop(Looper.java:313)
```

2024-03-28 22:54 UTC, DmitrijEgorow commented
Неконсистентное состояние: при пустой истории поиска мы не показываем заголовок и кнопку
![Screenshot_20240328_234641](https://github.com/Semiteplov/PlaylistMaker/assets/36837067/db6197cd-75a5-4126-9a7e-316cf09a5ce0)

2024-03-28 22:54 UTC, DmitrijEgorow commented
Кнопка не соответствует макетам: только первая буква должна быть заглавной
![Screenshot_20240328_233703](https://github.com/Semiteplov/PlaylistMaker/assets/36837067/b86f6364-dcb6-4294-8c2b-dc599f4962cb)

2024-03-29 23:29 UTC, Semiteplov commented on app/src/main/java/com/example/playlistmaker/media/ui/fragments/FavoriteTracksFragment.kt
>      private val binding get() = _binding!!
схожей с чем?

2024-03-29 23:47 UTC, Semiteplov commented on app/src/main/java/com/example/playlistmaker/media/ui/fragments/FavoriteTracksFragment.kt
>      private val binding get() = _binding!!
не очень понимаю в чем проблема

2024-03-31 18:20 UTC, DmitrijEgorow commented on app/src/main/java/com/example/playlistmaker/media/ui/fragments/FavoriteTracksFragment.kt
>      private val binding get() = _binding!!
[Вот в этой строчке](https://github.com/Semiteplov/PlaylistMaker/blob/813fcb8f92d7cafd84578640991da72f14d9f770/app/src/main/java/com/example/playlistmaker/search/ui/fragments/SearchFragment.kt#L273) ты обнуляешь binding – это правильно, так нужно делать для фрагментов
А [в этой строчке](https://github.com/Semiteplov/PlaylistMaker/blob/813fcb8f92d7cafd84578640991da72f14d9f770/app/src/main/java/com/example/playlistmaker/search/ui/fragments/SearchFragment.kt#L26) используется оператор !!, который выбрасывает NPE (в runtime, кстати)

2024-03-31 19:42 UTC, Semiteplov commented on app/src/main/java/com/example/playlistmaker/media/ui/fragments/FavoriteTracksFragment.kt
>      private val binding get() = _binding!!
это я понимаю, как это можно исправить?

2024-04-03 08:02 UTC, DmitrijEgorow commented on app/src/main/java/com/example/playlistmaker/media/ui/fragments/FavoriteTracksFragment.kt
>      private val binding get() = _binding!!
А зачем вообще два байндинга здесь?

2024-04-03 08:05 UTC, DmitrijEgorow commented on app/src/main/java/com/example/playlistmaker/media/ui/fragments/FavoriteTracksFragment.kt
>      private val binding get() = _binding!!
Можно даже посмотреть в сторону делагата, [например, такой типичный код](https://github.com/mrmacgood71/weather-app/blob/fb1e0b7a3e51ffbc9cc0e430688d9118a4f9faea/core/src/main/java/it/macgood/core/extension/ViewBinding.kt#L23)

2024-04-10 07:37 UTC, merged